### ISSUE TITLE
Remove fake @id from the pretty markup representation 

### ISSUE THREAD

**Issue by Gnomus042** [google/schemarama#10]
Fake @id field needs to be removed from the pretty markup representation

**Comment by danbri** [comment]
(thanks @jvandriel and @Aaranged for flagging this)

**Comment by Gnomus042** [comment]
Should be fixed with the last change :) 
```
{
  "@context": "https://schema.org",
  "@type": "Person",
  "name": "George Bush",
  "disambiguatingDescription": "41st President of the United States",
  "children": {
    "@type": "Person",
    "name": "George W. Bush",
    "disambiguatingDescription": "43rd President of the United States"
  }
}
```
![image](https://user-images.githubusercontent.com/23460931/98395326-c2166c80-2064-11eb-954c-2dcbf28f30e9.png)

**Comment by danbri** [comment]
Pushed to webschemas, see 

* https://webschemas.org/Book#eg-0400
* https://webschemas.org/ArchiveOrganization#eg-0254
* https://webschemas.org/Product#eg-0010

Thanks all :)

**Comment by jvandriel** [comment]
Thanks @Gnomus042
