### ISSUE TITLE
in /demo/README.md explain how to use requirements.txt

### ISSUE THREAD

**Issue by danbri** [google/schemarama#2]
e.g. 

>  pip3 install -r requirements.txt

**Comment by Gnomus042** [comment]
Since PR #17 requires to run the demo only with docker, we probably don't need the requirements.txt instruction

**Comment by timothywsage** [comment]
Onnnnitttttt

**Comment by timothywsage** [comment]
[requirements.txt](https://github.com/google/schemarama/files/6489741/requirements.txt)

**Comment by timothywsage** [comment]
[readme (1).md](https://github.com/google/schemarama/files/6489820/readme.1.md)

[readme (1).md](https://github.com/google/schemarama/files/6489822/readme.1.md)

**Comment by timothywsage** [comment]
Why are they still coming up as links ??

**Comment by danbri** [comment]
I've updated the file
