### ISSUE TITLE
will schemarama validate html documents?

### ISSUE THREAD

**Issue by doktorbro** [google/schemarama#6]
i use schema properties inside html documents.

```html
<body itemscope itemtype="https://schema.org/Person">
<h1 itemprop="name">anatol</h1>
```

will schemarama validate my html documents?

**Comment by danbri** [comment]
It seems to work with your example, yes

screenshot here: https://twitter.com/danbri/status/1324420811223158788

using the test version at http://gnomus042.com/

**Comment by danbri** [comment]
@Gnomus042 reminds me to say "yes but... the current set of shapes we have probably won't give you the full validation experience you're hoping for"...

**Comment by ziodave** [comment]
> It seems to work with your example, yes
> 
> screenshot here: https://twitter.com/danbri/status/1324420811223158788
> 
> using the test version at http://gnomus042.com/

@danbri I think gnomus042 has been hacked as the browser is redirected to a scammy web site.

**Comment by Gnomus042** [comment]
Hi @ziodave ,
We moved the test website to https://schemarama-demo.site/, you can try this one
