### ISSUE TITLE
Schemarama bookmarklet (for 'check this page')

### ISSUE THREAD

**Issue by danbri** [google/schemarama#8]
It is difficult to add "check this URL" functionality into a clientside app, but a bookmarklet that injects JS into the currently viewed page can work similarly. We had some tests of this early on - where are we with this?

**Comment by Gnomus042** [comment]
@danbri, it's not in schemarama, but I have it somewhere locally. It is probably outdated, I can make an update. As an option, for remote resources, we can add an opportunity to load data from remote webpages to the demo.

**Comment by danbri** [comment]
I have this but it isn't working for me: https://gist.github.com/danbri/4d4d7049ef765eb2b21bd943ac303b04

**Comment by Gnomus042** [comment]
URLs validation feature added to the demo
