### ISSUE TITLE
Consider contributing a PR for the (ruby-based) opensource Structured Data Linter, to use the prettyHTML component

### ISSUE THREAD

**Issue by danbri** [google/schemarama#9]
https://github.com/structured-data/linter

/cc @gkellogg @jvandriel @jaygray0919 

(there could also be a larger conversation about having the linter use https://github.com/ruby-rdf/shex and potential for interop testing...)

From a quick chat with @gkellogg:

> 'The structured view of examples would fit in pretty well with our system.'

**Comment by gkellogg** [comment]
Any help on these issues, and others greatly appreciated. 

Examples are built with a Rake task after importing raw examples from the schemaorg repo. Adding another tab for a structured view should be straightforward. 

Also, the Ruby ShEx implementation is a bit out of date, and could use some love. https://github.com/ruby-rdf/shex.

**Comment by danbri** [comment]
Thanks Gregg! 

BTW a while back, @gkellogg also [integrated](https://github.com/schemaorg/schemaorg/blob/main/.travis.yml) the Ruby Linter into schema.org's repo a while back, and we have been slow at updating the examples there to fix the various problems identified. Recently @RichardWallis has been making progress on that, and by happy coincidence Richard and @Gnomus042 spent last week integrating Schemarama into the "Examples" tab of Schema.org. Richard - could you be persuaded to take a look at helping with doing the same on the SD Linter?

<p align="center">
  <img width="800" src="https://pbs.twimg.com/media/EmHl297W0AEBXP6?format=jpg&name=medium">
</p>

**Comment by gkellogg** [comment]
The linter supports a structured view for examples (e.g. eg-0427 "structured" in http://linter.structured-data.org/examples/schema.org/Person/ and in [linted results](http://linter.structured-data.org/?url=http:%2F%2Flinter.structured-data.org%2Fexamples%2Fschema.org%2Feg-0427-jsonld.html)).

Any other changes are largely stylistic. Otherwise, I'm not clear on what the specific action is.
